# Generated by Django 5.1.1 on 2024-12-10 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer_bemodel',
            name='bemodel',
        ),
        migrations.AddField(
            model_name='answer_bemodel',
            name='behavior_model_a_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first_part', to='tasks.behaviormodel_a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer_bemodel',
            name='behavior_model_a_2',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='last_part', to='tasks.behaviormodel_a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer_bemodel',
            name='behavior_model_b',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='middle_part', to='tasks.behaviormodel_b'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer_bemodel',
            name='sub_function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_bemodels', to='tasks.subfunction'),
        ),
    ]
