# Generated by Django 5.1.1 on 2024-12-10 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_answer_bemodel_behavior_model_a_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_bemodel',
            name='behavior_model_a_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='middle_part', to='tasks.behaviormodel_a'),
        ),
        migrations.AlterField(
            model_name='answer_bemodel',
            name='behavior_model_b',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='last_part', to='tasks.behaviormodel_b'),
        ),
    ]
