# Generated by Django 5.1.1 on 2024-12-10 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_answer_bemodel_behavior_model_a_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubFunctionVarValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('subfunction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='var_values', to='tasks.subfunction')),
                ('var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.behaviormodel_a')),
            ],
        ),
    ]
