# Generated by Django 5.1.1 on 2024-12-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_protestanswer_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subfunction',
            name='hosoku',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='hosoku',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
