# Generated by Django 5.1.1 on 2024-12-14 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_subfunction_hosoku_task_hosoku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_bemodel',
            name='behavior_model_a_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='var1', to='tasks.behaviormodel_a'),
        ),
        migrations.AlterField(
            model_name='answer_bemodel',
            name='behavior_model_a_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='var2', to='tasks.behaviormodel_a'),
        ),
        migrations.AlterField(
            model_name='answer_bemodel',
            name='behavior_model_b',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relate', to='tasks.behaviormodel_b'),
        ),
        migrations.AlterField(
            model_name='task_answer_bemodel',
            name='behavior_model_a_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_var1', to='tasks.behaviormodel_a'),
        ),
        migrations.AlterField(
            model_name='task_answer_bemodel',
            name='behavior_model_a_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_var2', to='tasks.behaviormodel_a'),
        ),
        migrations.AlterField(
            model_name='task_answer_bemodel',
            name='behavior_model_b',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_relate', to='tasks.behaviormodel_b'),
        ),
        migrations.CreateModel(
            name='BehaviorModel_C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_choices', to='tasks.task')),
            ],
        ),
    ]
