# Generated by Django 5.1.1 on 2024-12-14 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_answer_bemodel_behavior_model_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_bemodel',
            name='behavior_model_c',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inout', to='tasks.behaviormodel_c'),
        ),
        migrations.AlterField(
            model_name='task_answer_bemodel',
            name='behavior_model_c',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_inout', to='tasks.behaviormodel_c'),
        ),
    ]
