# Generated by Django 5.1.1 on 2024-12-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_answer_bemodel_behavior_model_c_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer_bemodel',
            name='behavior_model_c',
        ),
        migrations.RemoveField(
            model_name='task_answer_bemodel',
            name='behavior_model_c',
        ),
        migrations.DeleteModel(
            name='BehaviorModel_C',
        ),
    ]
