# Generated by Django 5.1.1 on 2024-12-16 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_remove_answer_bemodel_behavior_model_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_bemodel',
            name='behavior_model_a_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='var1', to='tasks.subfunctionvarvalue'),
        ),
        migrations.AlterField(
            model_name='answer_bemodel',
            name='behavior_model_a_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='var2', to='tasks.subfunctionvarvalue'),
        ),
        migrations.AlterField(
            model_name='task_answer_bemodel',
            name='behavior_model_a_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_var1', to='tasks.taskvarvalue'),
        ),
        migrations.AlterField(
            model_name='task_answer_bemodel',
            name='behavior_model_a_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_var2', to='tasks.taskvarvalue'),
        ),
    ]
