# Generated by Django 5.1.1 on 2024-12-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_answer_bemodel_behavior_model_a_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hosoku',
            field=models.TextField(),
        ),
    ]
