# Generated by Django 5.1.1 on 2024-12-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_task_hosoku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subfunction',
            name='hosoku',
            field=models.TextField(),
        ),
    ]
