# Generated by Django 5.1.1 on 2024-12-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_subfunction_hosoku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskvarvalue',
            name='value',
        ),
        migrations.AlterField(
            model_name='subfunctionvarvalue',
            name='value',
            field=models.IntegerField(),
        ),
    ]
