# Generated by Django 5.1.1 on 2024-12-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_remove_taskvarvalue_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskvarvalue',
            name='value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
